### PR TITLE
fix: metrics were not registered correctly, this simplifies the setup

### LINKED ISSUE #438: Initially failedSetup metrics don't get updated on later success
## Expected behavior
When an initially failed setup for a system subscription later on succeeds, the `app.lamassu.gbfs.subscription.failedsetup` metric should switch from 1.0 to 0.0 for this system.

## Observed behavior
The metric stays at value 1.0.

## Version of lamassu used (exact commit hash or JAR name)
0d14f97

## Data sets in use (links to GBFS feeds)
Manuelly created feed with initially invalid gbfs.json which I fixed after starting lamassu

## Further information
Reason for this issue (and probably some other gauge related issues), is the current MetricsService use of meterRegistry.gauge(), which will not update the metric for subsequent calls (see e.g. )

Testcase to reproduce:

```java

package org.entur.lamassu.metrics;

import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.entur.lamassu.model.provider.FeedProvider;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class MetricsServiceTest {

    @Test
    public void testRegisterSubscriptionSetup() {
        SimpleMeterRegistry meterRegistry = new SimpleMeterRegistry();
        MetricsService metricsService = new MetricsService(meterRegistry);
        FeedProvider fp = new FeedProvider();
        fp.setSystemId("TestSystem");

        metricsService.registerSubscriptionSetup(fp, false);
        assertEquals(1.0, meterRegistry.get(MetricsService.SUBSCRIPTION_FAILEDSETUP).gauge().value(), 0.01);

        metricsService.registerSubscriptionSetup(fp, true);
        assertEquals(0.0, meterRegistry.get(MetricsService.SUBSCRIPTION_FAILEDSETUP).gauge().value(), 0.01);
    }
}


```

### PR DESCRIPTION
**Pull request by testower**
### Summary

Fixes issues with registering metrics. Metrics are registered once per combination of name and tags - subsequent calls are lost. It is required to keep counters for each combination, which gets hairy. This PR simplifies the setup, removes the file error metrics, and removes version and file tags.

### Issue

Closes #438 

### Unit tests

Unit tests were added to reproduce the problems and verify solution.

### CODE REVIEW

File: src/main/java/org/entur/lamassu/metrics/MetricsService.java [hunk 1]
```diff
@@ -130,4 +100,63 @@ public void registerEntityCount(String entity, int entityCount) {
...
+    );
+  }
+
+  private AtomicInteger getCounter(
+    FeedProvider feedProvider,
+    Map<String, AtomicInteger> counterMap,
+    String metricName
+  ) {
+    AtomicInteger counter;
+    if (counterMap.containsKey(feedProvider.getSystemId())) {
```
Comment (hbruch) [inline src/main/java/org/entur/lamassu/metrics/MetricsService.java:134]: ~~I think we require either a Map of Maps of use systemId+metricName as key (preferred)~~ Sorry, the counterMap is already per metricName

**Review by hbruch — APPROVED** [review]
LGTM, thank you for the immediate response!
